
resource_types:
- name: docker-stack
  type: docker-image
  source:
    repository: neerajlnm/docker-stack

resources:
- name: repo
  type: git
  source:
    uri: https://github.com/SapInnovation/docker-elk
    branch: master

- name: stack
  type: docker-stack

jobs:
- name: test-resource
  serial: true
  plan:
  - get: repo
  - task: deploy-stack-service
    config:
      platform: linux
      image_resource:
       type: stack
      params:
       stackconfig: repo/docker-stack.yml
       service_name: sample
       wait_until_ready: 60
      volumes:
       - /var/run/docker.sock:/var/run/docker.sock
      privileged: true
